#!/bin/bash

if [ -z $DISPLAY ]; then
    dialog=dialog
else
    dialog=Xdialog
fi
tools=()

for script in `find ~/tools/ -mindepth 1 -type d `; do
    tools+=($script/`echo ${script##*/}`)
    #echo ${script##*/}
done
#declare -p tools
for i in "${!tools[@]}"; do
    toolName=`echo ${tools[$i]##*/}`
    options="$options $((i+1)) $toolName"
done
#echo $options
size=$((${#tools[@]}+10))
exec 3>&1
ch=$(${dialog} --clear --title ToolBox --menu Choose: ${size} 70 4 ${options} 2>&1 1>&3)

#echo $menu $options
wait=$?
3>&-
if [ "$ch" ] ; then #&& [ "$ch" != "255" ] && [ "$ch" != "0" ]
    /bin/bash ${tools[$((ch-1))]}
fi
